#+title: i3 Config

* About

  This is my i3 config.
  I'm making it public in case any one else wants
  to incorporate similar features into their own config.
  For the most part, it's just the default config with some minor tweaks:

  * Graphics mode set to 1920x1080 on startup
    (may need to change output to appropriate value,
    and change mode if desired)
  * Keyboard layout changed to Dvorak
  * Use i3status-rs instead of i3status (on Centos 8)

  That's it for now, but I might add more in the future.

* Additional Notes

  * To install i3 on Centos 8:
    * i3 is not included in official Centos 8 repositories,
      but is available from the [[https://copr.fedorainfracloud.org/coprs/djotaku/i3wm/][djotaku/i3wm]] copr repository
    * djotaku/i3wm is missing =i3status=,
      so you will need to install it (or an alternative) from another source.
      I use [[https://github.com/greshake/i3status-rust][i3status-rust]] ([[https://copr.fedorainfracloud.org/coprs/atim/i3status-rust/][copr]]).
      * After installing, copy example config
        from =/usr/share/doc/i3status-rust/examples/config.toml=
        to =~/.config/i3status-rust/config.toml=
        and alter if desired
        (I just use the example config)
      * Alter =bar= section in i3 config to use =i3status-rs=
        (see [[https://github.com/davisn/i3-config/tree/centos8][centos8]] branch for details)
